### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by MartinMSPedersen** [1995parham/AUT-Trax-Player#1]
**COPYRIGHT VIOLATION**

All my trax-code is placed under the GPL v2 or v3 license.

please explain why you have taken my code
https://github.com/MartinMSPedersen/GnuTrax/blob/master/src/org/traxgame/main/Traxboard.java
and replaced the coyright notice with your own and remove the license file. 

Now it looks like you have written the code yourself which it **not** the case.

**I own the copyright to the code.** You are welcome to use my code but you can't legally or morally claim
that you own the copyright to https://github.com/1995parham/AUT-Trax-Player/blob/master/src/traxcore.c

Regards
Martin

**Comment by 1995parham** [comment]
Hello, I changed your java codes into C so I think I can change the copyright. I just forgot to add LICENSE. Sorry for my mistake, I will add the license and your name as a contributor and thanks for mentioning that.

**Comment by 1995parham** [comment]
I try to correct copyright issues. If you think it is ok I will close this issue.
